version: '3'
services: 
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.7
    environment:
      - LOG_LEVEL=debug
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"
      - "16686:16686"
      - "9411:9411"
