version: '2'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.port=14267"]
      ports:
        - "14269"
        - "14268:14268"
        - "14267"
        - "14250:14250"
        - "9411:9411"
      restart: on-failure
      environment:
        - LOG_LEVEL=debug
      depends_on:
        - cassandra-schema

    jaeger-query:
      image: jaegertracing/jaeger-query
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
      ports:
        - "16686:16686"
        - "16687"
      restart: on-failure
      environment:
        - LOG_LEVEL=debug
      depends_on:
        - cassandra-schema

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: ["--reporter.type=tchannel", "--reporter.tchannel.host-port=jaeger-collector:14267"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      environment:
        - LOG_LEVEL=debug
      depends_on:
        - jaeger-collector

    cassandra:
      image: cassandra:3.9
      ports: 
        - "7000:7000"
        - "9042:9042"
        - "7199:7199"

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema
      depends_on:
        - cassandra
