version: '3'
services: 
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.7
    environment:
      - LOG_LEVEL=debug
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
