// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/pinger/service.proto

package pinger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_665d02c26c5f0711, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PingResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_665d02c26c5f0711, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type PingPongRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Delay                int64    `protobuf:"varint,2,opt,name=delay,proto3" json:"delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingPongRequest) Reset()         { *m = PingPongRequest{} }
func (m *PingPongRequest) String() string { return proto.CompactTextString(m) }
func (*PingPongRequest) ProtoMessage()    {}
func (*PingPongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_665d02c26c5f0711, []int{2}
}

func (m *PingPongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingPongRequest.Unmarshal(m, b)
}
func (m *PingPongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingPongRequest.Marshal(b, m, deterministic)
}
func (m *PingPongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingPongRequest.Merge(m, src)
}
func (m *PingPongRequest) XXX_Size() int {
	return xxx_messageInfo_PingPongRequest.Size(m)
}
func (m *PingPongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingPongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingPongRequest proto.InternalMessageInfo

func (m *PingPongRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PingPongRequest) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

type PingPongResponse struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingPongResponse) Reset()         { *m = PingPongResponse{} }
func (m *PingPongResponse) String() string { return proto.CompactTextString(m) }
func (*PingPongResponse) ProtoMessage()    {}
func (*PingPongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_665d02c26c5f0711, []int{3}
}

func (m *PingPongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingPongResponse.Unmarshal(m, b)
}
func (m *PingPongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingPongResponse.Marshal(b, m, deterministic)
}
func (m *PingPongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingPongResponse.Merge(m, src)
}
func (m *PingPongResponse) XXX_Size() int {
	return xxx_messageInfo_PingPongResponse.Size(m)
}
func (m *PingPongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingPongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingPongResponse proto.InternalMessageInfo

func (m *PingPongResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "iheanyi.goopentracingexample.pinger.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "iheanyi.goopentracingexample.pinger.PingResponse")
	proto.RegisterType((*PingPongRequest)(nil), "iheanyi.goopentracingexample.pinger.PingPongRequest")
	proto.RegisterType((*PingPongResponse)(nil), "iheanyi.goopentracingexample.pinger.PingPongResponse")
}

func init() { proto.RegisterFile("rpc/pinger/service.proto", fileDescriptor_665d02c26c5f0711) }

var fileDescriptor_665d02c26c5f0711 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x2a, 0x48, 0xd6,
	0x2f, 0xc8, 0xcc, 0x4b, 0x4f, 0x2d, 0xd2, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0xce, 0xcc, 0x48, 0x4d, 0xcc, 0xab, 0xcc, 0xd4, 0x4b, 0xcf,
	0xcf, 0x2f, 0x48, 0xcd, 0x2b, 0x29, 0x4a, 0x4c, 0x06, 0x29, 0xab, 0x48, 0xcc, 0x2d, 0xc8, 0x49,
	0xd5, 0x83, 0x68, 0x51, 0x52, 0xe7, 0xe2, 0x0e, 0xc8, 0xcc, 0x4b, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x95, 0x94, 0xb8, 0x78, 0x20, 0x0a, 0x8b, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0x84, 0xb8, 0x58, 0x92, 0xf2, 0x53, 0x2a, 0xa1, 0xca, 0xc0, 0x6c, 0x25, 0x47,
	0x2e, 0x7e, 0x90, 0x9a, 0x80, 0x7c, 0x22, 0x0c, 0x14, 0x12, 0xe1, 0x62, 0x4d, 0x49, 0xcd, 0x49,
	0xac, 0x94, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0x70, 0x94, 0xd4, 0xb8, 0x04, 0x10, 0x46,
	0xe0, 0xb6, 0xca, 0xe8, 0x1d, 0x23, 0x17, 0x5b, 0x00, 0xd8, 0x0b, 0x42, 0xd9, 0x5c, 0x2c, 0x20,
	0x96, 0x90, 0x81, 0x1e, 0x11, 0x1e, 0xd6, 0x43, 0xf2, 0xad, 0x94, 0x21, 0x09, 0x3a, 0xa0, 0x6e,
	0x29, 0xe7, 0xe2, 0x80, 0xb9, 0x4f, 0xc8, 0x84, 0x68, 0xed, 0x48, 0x21, 0x22, 0x65, 0x4a, 0xa2,
	0x2e, 0x88, 0xc5, 0x4e, 0x1c, 0x51, 0x6c, 0x10, 0xa9, 0x24, 0x36, 0x70, 0xf4, 0x1a, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xc8, 0xe2, 0xdc, 0x65, 0xfa, 0x01, 0x00, 0x00,
}
